#!/usr/bin/env bash
set -euo pipefail

# Change the macOS MLX Whisper model stored in tigris-whisper.env.

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$REPO_DIR/tigris-whisper.env"
CONTROL_SCRIPT="$REPO_DIR/scripts/control_mac_app.sh"

usage() {
    cat <<EOF
Usage: ./scripts/change_mlx_model.sh [model|profile] [--restart]

Profiles:
  balanced       mlx-community/whisper-large-v3-turbo-q4
  fast           mlx-community/whisper-small-mlx-q4
  very-fast      mlx-community/whisper-base-mlx-q4
  best-accuracy  mlx-community/whisper-large-v3-turbo

Options:
  --restart      Restart the macOS app after saving the model
  -h, --help     Show this help

Run with no arguments for an interactive picker.
EOF
}

model_for_profile() {
    case "$1" in
        balanced|1)      echo "mlx-community/whisper-large-v3-turbo-q4" ;;
        fast|2)          echo "mlx-community/whisper-small-mlx-q4" ;;
        very-fast|3)     echo "mlx-community/whisper-base-mlx-q4" ;;
        best-accuracy|4) echo "mlx-community/whisper-large-v3-turbo" ;;
        *)               echo "$1" ;;
    esac
}

profile_for_model() {
    case "$1" in
        mlx-community/whisper-large-v3-turbo-q4) echo "balanced" ;;
        mlx-community/whisper-small-mlx-q4) echo "fast" ;;
        mlx-community/whisper-base-mlx-q4) echo "very-fast" ;;
        mlx-community/whisper-large-v3-turbo) echo "best-accuracy" ;;
        *) echo "custom" ;;
    esac
}

current_model() {
    if [ -f "$CONFIG_FILE" ]; then
        (
            # shellcheck source=/dev/null
            source "$CONFIG_FILE"
            printf "%s" "${WHISPER_MLX_MODEL:-}"
        )
    fi
}

choose_interactive() {
    local reply=""
    echo "Choose the local Whisper model for this Mac:"
    echo "  All choices below are multilingual Whisper models, not English-only models."
    echo "  Language list: https://github.com/openai/whisper/blob/main/whisper/tokenizer.py"
    echo ""
    echo "  1. Balanced (recommended): large-v3-turbo-q4 — multilingual, good accuracy, quantized"
    echo "  2. Fast: small-mlx-q4 — multilingual, lower latency, less accurate"
    echo "  3. Very fast: base-mlx-q4 — multilingual, shortest dictation, noticeably less accurate"
    echo "  4. Best accuracy: large-v3-turbo — multilingual, larger download/RAM"
    printf "Model choice [1]: "
    if [ -r /dev/tty ]; then
        read -r reply < /dev/tty || reply=""
    else
        read -r reply || reply=""
    fi
    model_for_profile "${reply:-1}"
}

write_config() {
    local model="$1"
    local profile
    profile="$(profile_for_model "$model")"
    {
        echo "# Generated by scripts/change_mlx_model.sh. Edit this file or rerun the script to change the model."
        printf 'export TIGRIS_MODEL_PROFILE=%q\n' "$profile"
        printf 'export WHISPER_MLX_MODEL=%q\n' "$model"
    } > "$CONFIG_FILE"
}

restart_if_requested() {
    local restart="$1"
    [ "$restart" = "1" ] || return 0
    if [ "$(uname -s)" != "Darwin" ]; then
        echo "Saved. Restart manually on this platform."
        return 0
    fi
    echo "Restarting tigris-whisper app..."
    bash "$CONTROL_SCRIPT" restart
}

RESTART=0
MODEL_ARG=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --restart) RESTART=1 ;;
        -h|--help) usage; exit 0 ;;
        *)
            if [ -n "$MODEL_ARG" ]; then
                echo "Error: only one model/profile argument is allowed."
                usage
                exit 1
            fi
            MODEL_ARG="$1"
            ;;
    esac
    shift
done

OLD_MODEL="$(current_model || true)"
if [ -n "$MODEL_ARG" ]; then
    MODEL="$(model_for_profile "$MODEL_ARG")"
else
    [ -n "$OLD_MODEL" ] && echo "Current model: $OLD_MODEL"
    MODEL="$(choose_interactive)"
fi

write_config "$MODEL"

echo ""
echo "Saved model config: $CONFIG_FILE"
echo "Previous model: ${OLD_MODEL:-none}"
echo "Selected model: $MODEL"
echo ""
echo "First use downloads the model if it is not cached yet."
echo "Restart required for a running daemon/app to use the new model."

restart_if_requested "$RESTART"
