#!/usr/bin/env bash
set -euo pipefail

# Change the faster-whisper model stored in tigris-whisper.env (Linux).

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$REPO_DIR/tigris-whisper.env"

usage() {
    cat <<EOF
Usage: ./scripts/change_faster_whisper_model.sh [model|profile] [--restart]

Profiles:
  balanced       small          (~490 MB, good accuracy)
  fast           base           (~145 MB, lower latency)
  very-fast      tiny           (~75 MB, fastest)
  best-accuracy  large-v3-turbo (~1.6 GB, best CPU accuracy)

Or pass any faster-whisper model id directly (e.g. medium).

Options:
  --restart      Kill and restart the running daemon after saving
  -h, --help     Show this help

Run with no arguments for an interactive picker.
EOF
}

model_for_profile() {
    case "$1" in
        balanced|1)      echo "small" ;;
        fast|2)          echo "base" ;;
        very-fast|3)     echo "tiny" ;;
        best-accuracy|4) echo "large-v3-turbo" ;;
        *)               echo "$1" ;;
    esac
}

profile_for_model() {
    case "$1" in
        small)          echo "balanced" ;;
        base)           echo "fast" ;;
        tiny)           echo "very-fast" ;;
        large-v3-turbo) echo "best-accuracy" ;;
        *)              echo "custom" ;;
    esac
}

current_model() {
    if [ -f "$CONFIG_FILE" ]; then
        (
            # shellcheck source=/dev/null
            source "$CONFIG_FILE"
            printf "%s" "${FASTER_WHISPER_MODEL:-}"
        )
    fi
}

choose_interactive() {
    local reply=""
    echo "Choose the faster-whisper model:"
    echo "  All choices are multilingual Whisper models."
    echo "  Language list: https://github.com/openai/whisper/blob/main/whisper/tokenizer.py"
    echo ""
    echo "  1. Balanced (default): small          — ~490 MB, good accuracy"
    echo "  2. Fast:               base            — ~145 MB, lower latency"
    echo "  3. Very fast:          tiny            — ~75 MB, fastest"
    echo "  4. Best accuracy:      large-v3-turbo  — ~1.6 GB, slower on CPU"
    printf "Model choice [1]: "
    if [ -r /dev/tty ]; then
        read -r reply < /dev/tty || reply=""
    else
        read -r reply || reply=""
    fi
    model_for_profile "${reply:-1}"
}

write_config() {
    local model="$1"
    local profile
    profile="$(profile_for_model "$model")"
    # Preserve existing Mac keys if present; only update the Linux model key.
    local tmp
    tmp="$(mktemp)"
    if [ -f "$CONFIG_FILE" ]; then
        grep -v '^export FASTER_WHISPER_MODEL=' "$CONFIG_FILE" > "$tmp" || true
        grep -v '^# Generated by scripts/change_faster_whisper' "$tmp" > "${tmp}.2" && mv "${tmp}.2" "$tmp" || true
    fi
    {
        cat "$tmp"
        printf 'export FASTER_WHISPER_MODEL=%q\n' "$model"
    } > "$CONFIG_FILE"
    rm -f "$tmp"
}

restart_if_requested() {
    [ "$1" = "1" ] || return 0
    echo "Stopping any running faster-whisper daemon…"
    pkill -f "faster_whisper_server.py" 2>/dev/null || true
    echo "Restart ./run.sh to start with the new model."
}

RESTART=0
MODEL_ARG=""

while [ "$#" -gt 0 ]; do
    case "$1" in
        --restart) RESTART=1 ;;
        -h|--help) usage; exit 0 ;;
        *)
            if [ -n "$MODEL_ARG" ]; then
                echo "Error: only one model/profile argument is allowed."
                usage; exit 1
            fi
            MODEL_ARG="$1"
            ;;
    esac
    shift
done

OLD_MODEL="$(current_model || true)"
if [ -n "$MODEL_ARG" ]; then
    MODEL="$(model_for_profile "$MODEL_ARG")"
else
    [ -n "$OLD_MODEL" ] && echo "Current model: $OLD_MODEL"
    MODEL="$(choose_interactive)"
fi

write_config "$MODEL"

echo ""
echo "Saved model config: $CONFIG_FILE"
echo "Previous model: ${OLD_MODEL:-none}"
echo "Selected model: $MODEL"
echo ""
echo "First use downloads the model if it is not cached yet."
echo "Restart ./run.sh for the new model to take effect."

restart_if_requested "$RESTART"
